export type LeaveRequest={request_type:string;start_date:string;end_date:string;status:string;amount_days?:number|null;amount_hours?:number|null};export type LeaveAdjustment={adjustment_type:string;adjustment_days:number;source_type?:string|null};
function toDateOnly(v:string|Date){const d=v instanceof Date?v:new Date(`${v}T00:00:00`);return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function completedMonths(j:Date,a:Date){let m=(a.getFullYear()-j.getFullYear())*12+(a.getMonth()-j.getMonth());if(a.getDate()<j.getDate())m-=1;return Math.max(0,m)}
function completedYears(j:Date,a:Date){let y=a.getFullYear()-j.getFullYear();const an=new Date(a.getFullYear(),j.getMonth(),j.getDate());if(a<an)y-=1;return Math.max(0,y)}
function addYears(d:Date,y:number){const r=new Date(d);r.setFullYear(r.getFullYear()+y);return r}
export function calculateLeaveEntitlement(joinedAtValue:string|null,asOfValue=new Date()){if(!joinedAtValue)return{baseGrantedDays:0,months:0,years:0,periodStart:null as string|null,periodEnd:null as string|null,description:"입사일 미등록"};const j=toDateOnly(joinedAtValue),a=toDateOnly(asOfValue),months=completedMonths(j,a),years=completedYears(j,a);const baseGrantedDays=years<1?Math.min(months,11):Math.min(25,15+Math.floor((years-1)/2));const s=addYears(j,years),e=addYears(s,1);e.setDate(e.getDate()-1);return{baseGrantedDays,months,years,periodStart:s.toISOString().slice(0,10),periodEnd:e.toISOString().slice(0,10),description:years<1?"1년 미만: 1개월 개근 시 1일":"1년 이상: 15일 + 장기근속 가산"}}
function countWeekdays(start:string,end:string){let d=toDateOnly(start);const last=toDateOnly(end);let c=0;while(d<=last){const day=d.getDay();if(day!==0&&day!==6)c++;d.setDate(d.getDate()+1)}return c}
export function requestToDays(req:LeaveRequest){if(req.amount_days!=null)return Number(req.amount_days);if(req.amount_hours!=null)return Number(req.amount_hours)/8;if(req.request_type==="half_am"||req.request_type==="half_pm")return .5;if(req.request_type==="hourly")return 0;return countWeekdays(req.start_date,req.end_date)}
export function calculateUsedDays(reqs:LeaveRequest[],includePending:boolean){const statuses=includePending?new Set(["approved","pending"]):new Set(["approved"]);const useTypes=new Set(["annual","half_am","half_pm","hourly","special","substitute","compensatory","comp_leave_use"]);return reqs.filter(r=>useTypes.has(r.request_type)).filter(r=>statuses.has(r.status)).reduce((s,r)=>s+requestToDays(r),0)}
export function calculateAdjustmentDays(adjs:LeaveAdjustment[]){return adjs.reduce((s,i)=>s+Number(i.adjustment_days||0),0)}
export function calculateCompTimeEarnedDays(adjs:LeaveAdjustment[]){return adjs.filter(i=>i.adjustment_type==="comp_time_earned").reduce((s,i)=>s+Number(i.adjustment_days||0),0)}
